name: Release

# on:
#   push:
#     tags:
#       - 'v*'
# release:
#   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: yarn install
    - run: yarn pub-with-ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        PUBLISH_NPM_CLI: 'yarn'
