name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./water-pro

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: yarn
        run: yarn --version
      - name: Install JS dependencies
        run: pwd
      - name: ls
        run: ls
